### ISSUE TITLE
[1.18.2] - Crystal AIOT Breaks Bedrock When Vein Mining

### ISSUE THREAD

**Issue by ToxinZangoose** [will-y/crystal-tools#1]
Heya, love this mod to pieces and wanted to share a small bug.

I used the crystal aiot to mine several blocks of stone, specifically deepslate, and I had FTB Ultimine as a second vein miner since I like its version the most.

I ended up breaking bedrock with vein mining and the Crystal AIOT. I was not mining bedrock to begin with, but the vein mining or the 3x3 upgrade must have caused some kind of glitch that included it for some reason.

My upgrades to the AIOT were all the way up to Infinite Speed which I put 13 points into, along with enchanting it with indestructible using the Indestructible Gem mod.

I'm playing on 40.1.80 (Forge) and again, 1.18.2
I'm using your latest update for Crystal Tools as well.

Thank you for this awesome mod, I am excited to see what you add from here on!

**Comment by will-y** [comment]
Thanks for using it!
I will look into this now

**Comment by will-y** [comment]
This is now fixed in version 1.18.2-1.1.4 and in 1.19.2-1.2.1
Thanks for letting me know and I hope you continue to enjoy the mod!
