### ISSUE TITLE
Suggestion: Backpack Curios

### ISSUE THREAD

**Issue by WimpieRatte** [will-y/crystal-tools#10]
Might be an obvious one, because there are so many backpack mods out there that already do this, but would it be possible to allow the backpack to go into a Curios slot, with a shortcut key (e.g: "b") that we can customise to open it?
Or to have a way in the inventory (like a new tab) where we can switch to its contents like switching to a different tab in the inventory.

**Comment by will-y** [comment]
Yep. The curios integration was something that I had planned. I wanted to get a working version out first but I will be adding that soon

**Comment by will-y** [comment]
Added in 1.20.1-1.6.1
