### ISSUE TITLE
Crash after eating crystal apple

### ISSUE THREAD

**Issue by Taccio33** [will-y/crystal-tools#11]
It seams a conflict with "supersaturation" mod.
[crash-2024-05-22_00.01.41-server.txt](https://github.com/will-y/crystal-tools/files/15403725/crash-2024-05-22_00.01.41-server.txt)

**Comment by will-y** [comment]
Thanks, Will look into this a hopefully get a fix into the next version

**Comment by will-y** [comment]
This is an issue with supersaturation, I made a PR to their mod, if they merge it in it should fix the issue. I also added a change in the Crystal Apple so it won't crash anymore, but supersaturation won't work correctly with it.

**Comment by will-y** [comment]
Workaround available in 1.20.1-1.6.1. Fix will be on supersaturation's side.
