### ISSUE TITLE
1.20.1-1.7.0 Crash Server-side (BlockEntityWithoutLevelRenderer)

### ISSUE THREAD

**Issue by WimpieRatte** [will-y/crystal-tools#12]
Crashes during server startup.

Main error seems to be linked to the new tridents causing this crash on a standalone server:
[main/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: Could not find parent net/minecraft/client/renderer/BlockEntityWithoutLevelRenderer for class dev/willyelton/crystal_tools/renderer/CrystalTridentBlockEntityWithoutLevelRenderer in classloader cpw.mods.modlauncher.TransformingClassLoader@201a8ea7 on thread Thread[main,5,main]

(When running this locally, it's not a problem - only when starting a dedicated server.)

[latest.log](https://github.com/user-attachments/files/15534367/latest.log)
Error log attached.

**Comment by will-y** [comment]
Confirmed, I need to get better at remembering to test the server.

Should have a fix for it soon.

**Comment by will-y** [comment]
Fix created, release 1.7.1 out soon. Thanks for you help testing, clearly something I'm not very good at.
