### ISSUE TITLE
Backpack feedback

### ISSUE THREAD

**Issue by WimpieRatte** [will-y/crystal-tools#14]
Thought I'd shortly give some backpack feedback, as that's been requested in the description of the backpack :).
It became my favourite backpack (Used to love Traveler's Backpack the most until now) because of the size, auto pickup + filter functionality! (That was even before I learned of the deposit into chests feature.)

Some suggestions:
- The xp gain is way too fast. Could probably be 4 times slower and still be ok.
- How about compatability with inventory management mods like Quark or IPN? (With Quark, one can search the inventory, which can be useful for such a large backpack. And the add/extract all or stash all (shift clicking the add/extract buttons in Quark) buttons those mods provide are also nice.)
- When in the curios slot, maybe a way to access its contents in the inventory GUI, like a new tab? (Like the inventory tabs mod does for other chests)
- A way to go to the skills from inside the GUI? (That way I don't have to unequip it from Curios into my hand before seeing the skills.)
- A bigger filter area (maybe give it more upgrades like the size upgrades currently has, which can go infinite... or at least to a bigger maximum filter quantity.)
- Maybe a compression upgrade? Giving a button that, when clicked, compresses nuggets into ingots, etc. (Any recipe that can compress with 9 items (or some known recipes that use 4 items). Useful when mining those gold nuggets in the nether and needing some ingots for piglin trading.) So to not compress it to its most compressed state, but to compress each stack once.

**Comment by will-y** [comment]
Thanks for the suggestions! Glad you like it.

1. I noticed XP gain was fast too, I slowed it down a little compared to the other tools, but I can bring it down more
2. I can look into this, not sure how quark decides what is an inventory. What is IPN, not familiar with that.
3. I can try, not sure how to do this but should be able to look at some other mods
4. I already do this for the furnace, just slipped my mind to add it to the backpack
5. This should be possible. The reason I didn't add more initially were 1. I got lazy with the GUI and having to deal with more filter slots than container slots and vice versa was a little annoying and 2. scrolling slots were very annoying to create. I should be able to create a config option to increase the number of filter slots per filter row pretty easily, and also maybe add a few more rows.
6. Something like this should be possible. I would probably want to let the user choose specific compression recipes to use and let them select more as they leveled this upgrade?

**Comment by WimpieRatte** [comment]
IPN = Inventory Profile Next (https://modrinth.com/mod/inventory-profiles-next).
I just mentioned it as another inventory sorter/stash/extract type of mod, like what Quark does. (I used to use IPN until Quark updated to 1.20.1 as well. Another mod that do so, is Inventory Management (https://modrinth.com/mod/inventory-management))

Another suggestion:
7: Add r-click add functionality inside inventory (similar to bundles). (While inside your inventory, when you pick up an item with left click, you can right click it into the backpack. (The Bag of Holding (https://modrinth.com/mod/bag-of-holding) mod by Fuzs has this type of functionality.)

Another mod compatibility suggestion (more a nice to have):
8: Compatibility for shift + r-clicking with the backpack on a Crafting/Storage Terminal of Tom's Storage (https://modrinth.com/mod/toms-storage). (This is, of course, just a nice to have, because one can still stash things into a chest/barrel and extract those items into the terminal's storage via hoppers, etc.) Other mods like Applied Energistics (https://modrinth.com/mod/ae2) also have such terminals.

**Comment by will-y** [comment]
Thanks,
The bundle things should hopefully be pretty easy, not sure though.

For putting into inventories, I look for an inventory Capability. Those mods probably don't have the terminals acting as inventories. There could be blocks that act like inventories that might work, maybe an interface or storage bus or something in AE. I can try to see if I can add a compat layer for those mods to see if they have easy ways to insert from terminals.

**Comment by WimpieRatte** [comment]
oh, forgot to say.
Your idea on the nr 6 (custom compression recipies) is also cool.
Sounds harder to implement than just compressing everything, but probably safer, just in case something is irrevertable, lol.

**Comment by will-y** [comment]
I would like the users to have more control and it shouldn't be much harder to implement. Plus it gave me an idea for some more features and a way to help with the filter problem, if I can get it to work the way I want it to

**Comment by will-y** [comment]
Screen isn't done, but this is the general idea I have.

With this idea, filters + maybe more features will become their own screens to allow for more configuration

![compression_demo](https://github.com/will-y/crystal-tools/assets/3957023/951f65a7-5c45-44b4-a995-dab4e45f3ab7)

**Comment by WimpieRatte** [comment]
The screen looks super cool! :D

**Comment by will-y** [comment]
Added a lot of your suggestions in 1.7.4. Missing a couple of things but I added them to my ever growing TODO list.
I did nerf the skill points (just changed the default config), you can nerf more in the config although it will only change new backpacks not old ones.

Here's the changelog:
## 1.7.4
### Additions
- Adds a new backpack upgrade: Compression
  - You can configure which items you want to compress and the press a button to compress all of them (gold nugget -> gold ingot)
- Adds new backpack sub menus
  - Filter configuration screen
  - Compression configuration screen
- Adds ability to take items in and out of the backpack while you are in your inventory like the bundle
  - Right-click an empty slot to take the last stack out of the backpack
  - Right-click another item to insert it into the backpack
  - Right-click the backpack to take the last stack out of it
  - Right-click the backpack holding an item to insert that item
- Adds button to create filters matching the backpack's contents
- Adds button to clear current filters

### Changes
- Changes to the backpack interface
  - Added a button to go to the skill tree
  - Removed the filters from the base backpack screen and moved them to a new screen

**Comment by WimpieRatte** [comment]
Just noticed the update. exited about using it!!! :D
Thanks man!
