### ISSUE TITLE
Crash with Crystal Trident - [1.20.1]

### ISSUE THREAD

**Issue by ToxinZangoose** [will-y/crystal-tools#15]
Hello again, I found a crash on a server with Upgradable Crystal Tools when holding a crystal trident in the main hand.

[crash-2024-06-10_11.01.49-client.txt]
(https://github.com/user-attachments/files/15795288/crash-2024-06-10_11.01.49-client.txt)

This caused me to be unable to join the server and would crash me to desktop.

Thankfully, our server has a backup mod and we restored it before I made the trident.

If there's any way you could repair this, I would be glad to continue testing. Thank you!

**Comment by will-y** [comment]
Should be fixed in 1.7.3. Thanks for the report!
