### ISSUE TITLE
Backpack shortcut no longer working?

### ISSUE THREAD

**Issue by WimpieRatte** [will-y/crystal-tools#16]
I used to have "b" bound for opening the backpack (when it's in the curios slot), but for some reason the shortcut now no longer works after the latest update? I tried rebinding it as well, without success.

(Loving the new update, btw!)
(Also, hoping this is not something broken on my side.)

**Comment by will-y** [comment]
Very possible that I broke that. I will look into it in a little bit.

**Comment by will-y** [comment]
Should be fixed in 1.7.5. Thanks for the report, let me know if you come across any other issues. I had to rewrite and reorganize a lot of things in 1.7.4 so wouldn't be too surprised if there were more issues.

**Comment by WimpieRatte** [comment]
Thanks a lot! Will do! :D
