### ISSUE TITLE
Crystal backpack crash

### ISSUE THREAD

**Issue by qvertytwo** [will-y/crystal-tools#17]
Hello
I have encountered a recurring bug with the crystal backpack. It crashes when i try to add more than 122 stacks to the backpack
[crash-2024-08-06_14.49.18-client.txt](https://github.com/user-attachments/files/16510512/crash-2024-08-06_14.49.18-client.txt)

**Comment by will-y** [comment]
Thought I fixed this but I guess not. Are you on version 2.0.0? I will look into this later today.

**Comment by qvertytwo** [comment]
yep, mod version 2.0.0. neoforge version 21.0.146

**Comment by will-y** [comment]
Fixed in 2.0.1. Thank you for the report, let me know if you come across any other issues or have any suggestions!
