### ISSUE TITLE
1.20.1 - Skills and Experience Bug

### ISSUE THREAD

**Issue by ToxinZangoose** [will-y/crystal-tools#18]
Hello again,

I found an unintended problem with Crystal Tools and Improvable Skills 3.

By taking out experience from a book of skills, the crystal tool (in this case, an AIOT), the skills went from positive 35, down into the integer limit in the negatives when I went to put my experience back.

I'm unsure if this is a problem with Crystal Tools or Improvable Skills 3, but I wanted to let you know first before I uploaded a bug report to Improvable Skills 3's GitHub.

[Reforged Adventures - Online.txt](https://github.com/user-attachments/files/16840546/Reforged.Adventures.-.Online.txt)

Above is my modlist, this was tested on a Forge 47.3.7 server.

**Comment by will-y** [comment]
I'll look into this

**Comment by will-y** [comment]
I wasn't able to reproduce this. If you could, can you try to find what action exactly causes this in a creative world? From looking at the improvable skills code it is probably not their fault. I did find a bug where there can be a client server desync when adding skill points using experience. I don't think it is related to that, but it could be.

**Comment by ToxinZangoose** [comment]
From what I can gather, I tried to add experience to my AIOT while on a server. I then had a bit of lag spike, then the AIOT went into the negatives after I tried to put my experience back into the storage.

Might be an edge case, but I wanted to let you know about it.

**Comment by will-y** [comment]
No, it isn't an edge case. I accidentally broke adding points with experience in the last update. I will release an update to fix that soon.

**Comment by ToxinZangoose** [comment]
Ok, good. Thank you for fixing it! I appreciate it. :smiley:

**Comment by will-y** [comment]
Should be fixed in 1.7.7. Thanks for the report!
