### ISSUE TITLE
1.20.1: Crystal Bow compatibility with Supplementaries Quiver

### ISSUE THREAD

**Issue by WimpieRatte** [will-y/crystal-tools#19]
Hi there! :D

Found an interesting incompatibility now.
When using a crystal bow and I only have arrows in a supplementaries quiver, it doesn't shoot.
(It does the shooting animation, but no arrows get fired.)

I just had this with the quiver in my inventory - not sure if it will behave the same when the quiver is in my curios belt slot - can't test currently, but thought I'd mention the issue in the meantime.

Wishing you a great week further! :D

**Comment by will-y** [comment]
Which Minecraft version is this?

**Comment by will-y** [comment]
Oh, I see it in the title now sorry. I'll look into this now

**Comment by will-y** [comment]
Fixed in 1.7.8, should be up on curse and modrinth soon

**Comment by WimpieRatte** [comment]
This is why you're my favourite mod developer recently.
Every issue I've logged has been checked, confirmed and patched within mere hours.
I even told my buddy when I found the bug: "This guy is usually very quick on his responses, so I feel confident in reporting it."
Thank you - your professionalism is very appreciated!

**Comment by will-y** [comment]
Np. Thanks for playing and giving me good reports!
