### ISSUE TITLE
Crystal Elytra Lagging/Freezing Game

### ISSUE THREAD

**Issue by JMEllis2020** [will-y/crystal-tools#2]
I upgraded my crystal elytra to max and it broke the game. I think it has something to do with the health and armor bonuses it gives. This is my second one I've upgraded to max to test, I didn't do the health bonuses this time, but it still lagged out once I maxed it out

**Comment by JMEllis2020** [comment]
Oh, its also infinitely adding hearts to my health too, thats why I think its either the Health bonus or toughness or base armor upgrades. I'm going to test it on the chestplate and see if it does the same thing.

**Comment by will-y** [comment]
I have a fix for the infinite health part which should also fix the lag spike / crash. I know there is an issue with health not going back down when you take off armor or the elytra. I have tried to fix it many times before but nothing has worked. If you know of another mod that does something similar let me know and maybe that will help me get a fix for it.

**Comment by JMEllis2020** [comment]
The past two times when I loaded the game back up it reset, one time I got the Elytra off, but the health remained, so I stored stuff and drowned myself and it reset. I'm kinda new to using mods, so I have no clue if there are any available that would do that. It wasn't a shared world or hardcore or anything like that so I haven't lost much, I was just testing mods in a new world, trying to figure out what mods I want on a main world when I do start a real one. Everything else in the mod I've enjoyed though :)
Oh, I can't right click and place a torch sometimes with the AIOT in torch mode. The issue happened inside of a dungeon with a spawner, so I don't know if there are some kind of limitations or something there. Also if I have torches in my off-hand and am using the pickaxe, I can't seem to place torches down in the situation. Not sure if it is conflicting with a feature of the pickaxe or what.

**Comment by JMEllis2020** [comment]
Also, I was curious if there was a way or plans to reset the skill points on the items or if there was a command to do that so I won't have to throw that Elytra away. Is there a command to give the items experience as well?

Sorry, I know that is kinda off subject, just figured I would ask :)

**Comment by will-y** [comment]
This is now fixed in 1.18-1.2.1 and 1.19-1.2.2.
I'll look into those issues as well.

I haven't considered adding a reset option, but that is something that I could do pretty easily.

There is an op command `/add_points <points>` that will add skill points to the tool you are currently holding in your main hand.
Although you shouldn't need to throw it away, it should work normally after you update to the next version in either 1.18 or 1.19.

**Comment by will-y** [comment]
> The past two times when I loaded the game back up it reset, one time I got the Elytra off, but the health remained, so I stored stuff and drowned myself and it reset. I'm kinda new to using mods, so I have no clue if there are any available that would do that. It wasn't a shared world or hardcore or anything like that so I haven't lost much, I was just testing mods in a new world, trying to figure out what mods I want on a main world when I do start a real one. Everything else in the mod I've enjoyed though :)
> 
> Oh, I can't right click and place a torch sometimes with the AIOT in torch mode. The issue happened inside of a dungeon with a spawner, so I don't know if there are some kind of limitations or something there. Also if I have torches in my off-hand and am using the pickaxe, I can't seem to place torches down in the situation. Not sure if it is conflicting with a feature of the pickaxe or what.

I created a new issue for these new bugs, I was able to replicate the error with the pickaxe but wasn't able to replicate the issue with the AIOT. Could you provide more details? Which version of the mod was it on?

**Comment by JMEllis2020** [comment]
1.2.1
I found a zombie spawner and broke in and it wouldn't let me place torches on the spawner or the mossy cobblestone, then I removed the spawner and it let me place one where the spawner was. It was just iffy where I could place stuff inside that dungeon spawner room with the AIOT.
Also, updated to 1.2.2, I'll try it out later tonight and see if the Elytra is giving me the same issues.

**Comment by JMEllis2020** [comment]
So I checked it out, and it worked for a while, but then slowly got laggy and then froze. It could be another mod at this point though, it was working well for like 5-10 minutes

**Comment by will-y** [comment]
Ok. I see this now but only in 1.19 for some reason, I'll look into it.

**Comment by JMEllis2020** [comment]
Sorry for all the trouble lol. I'll keep my Elytra this time. I'm sure you will get it working for 1.19. :) 

Did you end up figuring out the other issues?

**Comment by will-y** [comment]
It's not trouble, thanks for helping me find these issues. I did manage to fix the elytra and I fixed the issue with not being able to place torches in the off-hand with the pickaxe. I still haven't found anything with the torch mode though, I will try a few more things with that today and then I will get a release out that fixes these things hopefully later today.

**Comment by JMEllis2020** [comment]
Awesome, I'll be looking out for it :)

**Comment by will-y** [comment]
Versions for 1.19 and 1.18 are being approved on curse forge right now.

**Comment by JMEllis2020** [comment]
I'll check tomorrow and let you know if I have any issues with it. World of Warcraft has the pre-patch for their next expansion coming tomorrow and I wanted to play some before tomorrow changes and breaks everything in that game, or I would go ahead and check it out tonight lol.
