### ISSUE TITLE
Furnace Exp Boost upgrade doesn't seem to work + Reset option not available on Furnaces

### ISSUE THREAD

**Issue by Desempregago** [will-y/crystal-tools#22]
9 EXP from each smelt

https://github.com/user-attachments/assets/bec6c755-9afc-49c0-962a-53b6d5e3a91c

Crystal Tools 2.1.3

**Comment by Desempregago** [comment]
Also, furnaces doesn't keep their upgrades or skill points bought with XP

**Comment by will-y** [comment]
I will look into this tomorrow

**Comment by will-y** [comment]
The exp boost is for the minecraft experience generated from smelting, not the skill experience you gain. The reset button not showing up and the upgrades bought with XP are definitely bugs though.

**Comment by will-y** [comment]
Should be fixed in 2.1.4, thanks!
