### ISSUE TITLE
[Suggestion] Toggle Night Vision keybind

### ISSUE THREAD

**Issue by Desempregago** [will-y/crystal-tools#23]

**Comment by will-y** [comment]
Definitely something I can implement easily, will look at doing it soon

**Comment by will-y** [comment]
Added in 2.1.4. You can either hold the helmet in your hand and press the mode switch key, or press the mode switch key while not holding another crystal tool and it will toggle night vision.

**Comment by Desempregago** [comment]
Just noticed a bug. With Night Vision disabled, the sky flickers, as if the effect was begin constantly toggled on and off, while the lighting keeps being affected by the effect.

**Comment by will-y** [comment]
Weird, I'll look into it

**Comment by will-y** [comment]
It seemed to only happen on servers for some reason. I removed the instant removal when you disable it and that fixes it
