### ISSUE TITLE
[Suggestion] Curios compat for the Backpack

### ISSUE THREAD

**Issue by Desempregago** [will-y/crystal-tools#24]

**Comment by Desempregago** [comment]
This may be kind of a low priority thing or could even be unneeded.

**Comment by will-y** [comment]
This was added last version, but probably broke with the new version of Minecraft. I know there are now a bunch of different curios-like mods so I will have to see how each of them work

**Comment by will-y** [comment]
Added support for Accessories, Curios Continuation, and Adorned in version 2.1.6
