### ISSUE TITLE
1.21.1 - AIOT Bug with 3x3 mining on dirt, gravel, sand, etc.

### ISSUE THREAD

**Issue by ToxinZangoose** [will-y/crystal-tools#26]
Hello again,

I am writing this bug report to let you know that I found a small issue with the Crystal AIOT.

When mining in 3x3 mode, clay, sand, dirt, gravel or grass blocks do not get broken simultaneously, leading to blocks in the path that can't be traversed.

I tested the Crystal Shovel as well, the bug was not present when using the shovel.

Thank you for your time, I hope to see more new and exciting features added to this mod some day in the future. :smile:

**Comment by will-y** [comment]
Fixed in 2.1.7, thanks for the report as always!
