### ISSUE TITLE
High cost of experience to points can lead to exp duping

### ISSUE THREAD

**Issue by edotenseilove** [will-y/crystal-tools#27]
I have noticed a bug that when a player upgrades a generator to a high enaught level using experience (around 8 000 points or more [all bought in thousands] to spend and then used on sth)  the experiance gets added instaed of spent leeding to a player getting so much experiance that the upgrade menu gets confused and does not allow you to turn experiance to points but when the player deposits the experiance and lowers it down enaught the experiace can be turned to points again but the duping phenomenom persists.

Would it be possible to figure out a workaround to this issue. The easiest solution i think would be to create a hard cap of max points of experiance that can be turned to points so that the experiance cost would not go to a negatives which I assume is happening. I like to push the things to the extreme so i would not like that to be a sollution. But I understand that the issue is probably complex and there arent lots of solutions to choose from.

**Comment by will-y** [comment]
I limited the amount of xp scaling that happens to 500, so now each point should only be able to cost 510 levels, so adding 1000 levels won't overflow anymore.

Version 2.1.8 should be on curse soon

**Comment by edotenseilove** [comment]
Thank you I will give it a try
