### ISSUE TITLE
1.20.1 - Question About the Auto Repair perk

### ISSUE THREAD

**Issue by ToxinZangoose** [will-y/crystal-tools#5]
Hello,
I have to ask about the auto repair skill for the Crystal AIOT.

Is it meant to automatically fully repair the tool after a specified amount of time or does it repair the tool little by little over a specific time?

I sunk 50 skill points into Auto Repairing and it seems that it isn't repairing the AIOT, it also voided an enchantment from the indestructible enchantment mod when I reset the tool's skill points.

I have also put 50 points into the infinite unbreaking skill and it seems that the tool still gets damaged by the same amount of durability even at 50 percent.

Please let me know if this is intended or is a bug, thank you for a great mod!

**Comment by will-y** [comment]
It is meant to repair the tool slowly over time. It doesn't work while the item is in your hand. I did just mess with the though so I might have broken something.

I will look into the infinite unbreaking skill to make sure that is working properly.

The tools shouldn't be enchantable in the first place. I can check to see if that is a problem on my end or a problem with the other mod.

Thanks for the report!

**Comment by will-y** [comment]
I fixed a small bug related to durability and tools taking damage and made tools not be enchantable. I'm not sure about the auto repair and unbreaking issues, I tested those and they seemed to both be working fine with me, it might be some weird mod interaction but I'm not sure. If you are still seeing the issues I can maybe try to look into some interactions to see if I can find some issues.

**Comment by ToxinZangoose** [comment]
Heya, got a small update that I wanted to share with you.
I tried out the unbreaking skill again and it works perfectly now, no damage is done to the tool at all.

I have however run into another problem with this mod.

I think it could be because of some new update with NeoForge or Forge itself but the crystal pickaxe has a very slow mining speed like breaking deepslate for regular stone.

I've tried disabling several mods but this one seems the be the cause of the issue, no other tools are affected as far as I know.

If you could check and make sure the tier of the crystal pickaxe is correct, I'd hope this would clear up any issue.

**Comment by will-y** [comment]
Sure I will check, can you let me know which version of Forge or NeoForge you are running?

**Comment by ToxinZangoose** [comment]
NeoForge version is 47.1.79 - Tested and confirmed to have block breaking issue
Forge version is 47.2.0 - Also tested and found the same block breaking problem

I've tried all versions of Crystal Tools available for 1.20.1

**Comment by will-y** [comment]
I tested on both of those versions and was unable to reproduce the issue. What other mods are you using?

**Comment by ToxinZangoose** [comment]
![image](https://github.com/will-y/crystal-tools/assets/79818060/9e09c19f-7eef-497c-a7a9-b9dd5135cf0a)
![image](https://github.com/will-y/crystal-tools/assets/79818060/f5a49ab8-fe6b-4ec5-82de-def4427554a8)
![image](https://github.com/will-y/crystal-tools/assets/79818060/4e41179f-a9a5-414d-ad01-f0dcabca477a)
![image](https://github.com/will-y/crystal-tools/assets/79818060/49036c25-1709-4968-8bd5-27a5f54cea8c)

I had to upload several screenshots in order to capture all of the mods in my folder.
I hope this helps!
