### ISSUE TITLE
1.18.2 Elytra and AIOT recipes not showing

### ISSUE THREAD

**Issue by Izunyaaan** [will-y/crystal-tools#6]
I can't seem to find the crafting recipe on JEI. The other tools seem to show just fine. Is there a mod I'm supposed to add along with this one?

**Comment by Izunyaaan** [comment]
I found out the reason.
crystal_aiot.json:
```
{
  "type": "crystal_tools:crystal_aiot_recipe"
}

```

crystal_elytra.json:
```
{
    "type": "crystal_tools:crystal_elytra_recipe"
}
```

I am using the 1.3.0 version XD

**Comment by will-y** [comment]
I am assuming it is because they are custom recipes to handle the skill point transfers. I can try to look into making them show up in JEI.

**Comment by Izunyaaan** [comment]
Ah, so I can actually craft them?

**Comment by will-y** [comment]
Yes, you should be able to craft them they just won't show up in JEI. I just got it to show up in JEI, there will be a release either later today or tomorrow that fixes it.
![image](https://github.com/will-y/crystal-tools/assets/3957023/aecd9a21-adc3-43c8-b31c-87d0cf47300a)

**Comment by will-y** [comment]
Fixed in 1.18.2-1.3.1
Will be fixed in 1.19 and 1.20 soon

**Comment by Izunyaaan** [comment]
Thank you! For both the fixes

**Comment by will-y** [comment]
NP, glad you like the mod! Let me know if you run into any more issues!
