### ISSUE TITLE
1.18.2 Crystal bow doesn't work with quivers

### ISSUE THREAD

**Issue by Izunyaaan** [will-y/crystal-tools#7]
I'm using Nyf's Quiver & Nyf's extended quivers. Crystal bow doesn't seem to work with the Netherite-diamond quiver. Haven't tried with the rest.

**Comment by will-y** [comment]
I'll see what they are doing and try to find a way to work with that

**Comment by Izunyaaan** [comment]
Thanks mate, can't live without the quivers anymore but this mod is awesome too 🤣

**Comment by will-y** [comment]
I was able to fix a few issues and it now fires arrows stored in a quiver when it is in a curios slot. Not 100% sure this is fixed in all cases, let me know if you run into issues once I push the new version.

**Comment by will-y** [comment]
Fixed in 1.18.2-1.3.1
Will be fixed in 1.19 and 1.20 soon
