### ISSUE TITLE
Suggestion: Experience Blacklist

### ISSUE THREAD

**Issue by WimpieRatte** [will-y/crystal-tools#9]
It would be nice to be able to blacklist some entities or items, like the "MmmMmmMmmMmm" mod's target dummy, from giving experience.
In our modpack, we could just keep shooting the target dummy with arrows until we maxed out a crystal bow. Would be nice to prevent something like that, if possible?

**Comment by will-y** [comment]
Yeah that should be possible. I can add a blacklist tag that you should be able to add entities to.

**Comment by will-y** [comment]
Added in 1.20.1-1.6.1

**Comment by WimpieRatte** [comment]
For reference to anyone else who wants to use your change, I blacklisted the target dummy as follows:

1. Install CraftTweaker mod
2. Create a new .zs file in ./scripts/
3. add the following line in the .zs file:
`<tag:entity_types:crystal_tools:entity_blacklist>.add(<entitytype:dummmmmmy:target_dummy>);`
(Just replace "dummmmmmy:target_dummy" with whatever mob or entity you want to blacklist.)

The .zs file is executed/applied when your world loads

**Comment by will-y** [comment]
If you don't use CraftTweaker, you can also add to the tag via datapacks.

Add a file `entity_blacklist.json` in the datapack in the location `crystal_tools/tags/entity_types` that looks like
```json
{
  "values": [
    "minecraft:armor_stand"
  ]
}
```

I will add this to the readme as well
